action: difference
name-path-mappings:
  - name: S1
    paths: [example/r.hpp]
  - name: S2
    paths: [example/rl.hpp]
  - name: S3
    paths: [example/rc.hpp]
  - name: S4
    paths: [example/rcl.hpp]
  - name: S5
    paths: [example/i.hpp]
  - name: S6
    paths: [example/il.hpp]
  - name: S7
    paths: [example/ic.hpp]
  - name: S8
    paths: [example/icl.hpp]
options:
  minimum_trace_size: 1
  only_named_nodes: false
  language: cpp
expressions:
  - left-side: [S2, S8]
    right-side: [S3, S5]
    labels:
      - logging_1
      - logging
      - F
  - left-side: [S2, S8]
    right-side: [S1, S7]
    labels:
      - logging_2
      - logging
      - F
  - left-side: [S3, S8]
    right-side: [S1, S6]
    labels:
      - checked
      - F
  - left-side: [S5, S6]
    right-side: [S1, S4]
    labels:
      - iterative
      - F
  - left-side: [S7]
    right-side: [S3, S5]
    labels:
      - checked_and_iterative
      - F
  - left-side: [S2, S7]
    right-side: [S1, S5]
    labels:
      - logging_or_checked
      - O
run:
  - checked